---
# handlers file for ansible-role-nginx

- name: nginx configtest and reload
  command: /bin/true
  notify:
    - nginx configtest
    - nginx reload

- name: nginx configtest
  command: nginx -t
  become: yes

- name: nginx reload
  service:
    name: nginx
    state: reloaded
  become: true
